### ISSUE TITLE
doesn't install from cpan

### ISSUE THREAD

**Issue by drebolo** [PerlDancer/dancer2-session-json#2]
should your dist.ini have "[Prereqs] Dancer2 = 2"?

name    = Dancer2-Session-JSON
author  = David Golden <dagolden@cpan.org>
license = Apache_2_0
copyright_holder = David Golden
copyright_year   = 2013

[@DAGOLDEN]
:version = 0.035
AutoMetaResources.bugtracker.rt = 0
AutoMetaResources.bugtracker.github = user:dagolden

[Prereqs]
Dancer2 = 2

**Comment by cromedome** [comment]
Just released 0.002 to CPAN which should fix this.
